site_name: Easy-MkDocs
repo_url: https://github.com/aaronaddleman/easy-mkdocs
repo_name: easy-mkdocs
plugins:
  - monorepo
  - search
  - exclude-search:
      exclude:
        - projects/*
  - macros:
      include_dir: projects
theme:
  name: material
  features:
    - toc.integrate
    - content.tabs.link
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.snippets
  - abbr
  - def_list
  - toc:
      permalink: true
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
nav:
  - Home:
    - Index: index.md
  - Template Files:
    - intro: template_files/index.md
    - 0.0.1:
        index: template_files/0.0.1/docs/index.md

